version: "3"
services:
  app:
    build: .
    command: yarn dev
    ports:
      - "3333:3333"
    environment:
      - DB_HOST=database
      - BCRYPT_SALT= 10
      - JWT_SECRET=mfefkuhio3k2rjkofn2mbikbkwjhnkjfeline
    volumes:
      - ".:/usr/app"

  database:
    image: mongo
